### ISSUE TITLE
Not able to save the bookmark

### ISSUE THREAD

**Issue by shubhank-saxena** [ndom91/briefkasten#13]
### Describe the bug

I am trying to save the bookmark on the UI but it's throwing the error. 
Note - I am running my server on raspberry pi 4b

```
error - ReferenceError: performance is not defined
    at Object.start (webpack-internal:///(api)/./src/lib/helpers.js:27:24)
    at handler (webpack-internal:///(api)/./src/pages/api/bookmarks/index.js:119:72)
    at async Object.apiResolver (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:179:9)
    at async DevServer.runApi (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:381:9)
    at async Object.fn (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:497:37)
    at async Router.execute (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:213:36)
    at async DevServer.run (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:616:29)
    at async DevServer.run (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/dev/next-dev-server.js:532:20)
    at async DevServer.handleRequest (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:317:20) {
  page: '/api/bookmarks'
}
  30 |     serverTiming.timings = {
  31 |       total: {
> 32 |         start: performance.now(),
     |               ^
  33 |       },
  34 |     }
  35 |   },
  ```

### Reproduction

Run the server and save the bookmark

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) arm64 unknown
    Memory: 712.83 MB / 3.72 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 14.19.3 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 6.14.17 - /usr/bin/npm
  Browsers:
    Firefox: 91.9.1esr
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
@shubhank-saxena thanks for posting this!

I've just pushed an update that uses `new Date().getTime()` to get a unix timestamp, instead of `performance.now()` where it is not available. If you pull from `main` again and rebuild, you should be good to go here :+1:

**Comment by shubhank-saxena** [comment]
It's still showing unknown variable error for performance

```
error - (api)/src/lib/helpers.js (23:2) @ perf
error - ReferenceError: performance is not defined
    at perf (webpack-internal:///(api)/./src/lib/helpers.js:18:5)
    at Object.start (webpack-internal:///(api)/./src/lib/helpers.js:33:24)
    at handler (webpack-internal:///(api)/./src/pages/api/bookmarks/index.js:120:72)
    at async Object.apiResolver (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:179:9)
    at async DevServer.runApi (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:381:9)
    at async Object.fn (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:497:37)
    at async Router.execute (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:213:36)
    at async DevServer.run (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:616:29)
    at async DevServer.run (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/dev/next-dev-server.js:532:20)
    at async DevServer.handleRequest (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:317:20) {
  page: '/api/bookmarks'
}
  21 |
  22 | export const perf = () => {
> 23 |   return performance ? performance : { now: () => new Date().getTime() }
     |  ^
  24 | }
  25 |
  26 | export const range = (start, end) => {
  ```

**Comment by ndom91** [comment]
Hi @shubhank-saxena okay strange.. I've simplified that logic now a bit, can you give it another shot? Latest `main` branch :+1:

**Comment by shubhank-saxena** [comment]
Same error @ndom91 
```
error - (api)/src/lib/helpers.js (23:2) @ perf
error - ReferenceError: performance is not defined
    at perf (webpack-internal:///(api)/./src/lib/helpers.js:18:5)
    at Object.start (webpack-internal:///(api)/./src/lib/helpers.js:37:24)
    at handler (webpack-internal:///(api)/./src/pages/api/bookmarks/index.js:120:72)
    at async Object.apiResolver (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:179:9)
    at async DevServer.runApi (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:381:9)
    at async Object.fn (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:497:37)
    at async Router.execute (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:213:36)
    at async DevServer.run (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:616:29)
    at async DevServer.run (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/dev/next-dev-server.js:532:20)
    at async DevServer.handleRequest (/srv/dev-disk-by-label-media/Files/AppData/Config/briefkasten/briefkasten/node_modules/.pnpm/next@12.2.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:317:20) {
  page: '/api/bookmarks'
}
  21 |
  22 | export const perf = () => {
> 23 |   if (performance) {
     |  ^
  24 |     return performance
  25 |   } else {
  26 |     return { now: () => new Date().getTime() }
  ```

**Comment by ndom91** [comment]
Okay wtf, if it doesn't exist it should just go into the else branch :joy:

**Comment by ndom91** [comment]
Are you comfortable making changes to the code yourself? If so, can you try this?

```js
  if (!performance) {
    return { now: () => new Date().getTime() }
  } else {
    return performance
  }
```

Also follow up - I see you're using node 14, could you give node 16 a try if it still doesnt work?

**Comment by shubhank-saxena** [comment]
Sure. Let me give it a try

**Comment by shubhank-saxena** [comment]
Hey, @ndom91, same error. It looks as if the performance in this file is a variable assigned before the declaration. Was it supposed to be imported from some file?

**Comment by ndom91** [comment]
> Hey, @ndom91, same error. It looks as if the performance in this file is a variable assigned before the declaration. Was it supposed to be imported from some file?

Strange, no it's a node/browser api global afaik. 

I'll just remove it for now and use the slightly less accurate date.getTime(). 

This was mostly just for debugging and issue using the server-timing api anyway. 

Thanks for your patience!

**Comment by shubhank-saxena** [comment]
> > Hey, @ndom91, same error. It looks as if the performance in this file is a variable assigned before the declaration. Was it supposed to be imported from some file?
> 
> Strange, no it's a node/browser api global afaik.
> 
> I'll just remove it for now and use the slightly less accurate date.getTime().
> 
> This was mostly just for debugging an issue using the server-timing api anyway.
> 
> Thanks for your patience!

No worries @ndom91 😄

**Comment by ndom91** [comment]
@shubhank-saxena alright, pushed that change to `main`. Can you give it another shot?

**Comment by shubhank-saxena** [comment]
@ndom91 works like a charm 🚀 🚀

**Comment by shubhank-saxena** [comment]
Thank you so much for debugging it. I can finally now close all my tabs XD
