### ISSUE TITLE
Unable to login - Frontend indicated "Oops"

### ISSUE THREAD

**Issue by tj31moll** [ndom91/briefkasten#15]
### Describe the bug

I ran with docker config. I think I did all the step correctly but just changed ports of bk-app to 3066 for preference. However, everytime I load, I get:

`> briefkasten@0.8.0 start /app,
> next start,
ready - started server on 0.0.0.0:3066, url: http://localhost:3066,
warn  - You have enabled experimental features (legacyBrowsers, browsersListForSwc, images) in next.config.mjs.,
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.,
info  - SWC minify release candidate enabled. https://nextjs.link/swcmin,
TypeError: Cannot convert undefined or null to object,
    at Function.keys (<anonymous>),
    at Signin (/app/.next/server/pages/auth/signin.js:57:43),
    at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44),
    at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253),
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89),
    at $c (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98),
    at bd (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404),
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217),
    at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209),
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89),
TypeError: Cannot convert undefined or null to object,
    at Function.keys (<anonymous>),
    at Signin (/app/.next/server/pages/auth/signin.js:57:43),
    at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44),
    at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253),
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89),
    at $c (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98),
    at bd (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404),
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217),
    at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209),
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89),
TypeError: Cannot convert undefined or null to object,
    at Function.keys (<anonymous>),
    at Signin (/app/.next/server/pages/auth/signin.js:57:43),
    at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44),
    at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253),
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89),
    at $c (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98),
    at bd (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404),
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217),
    at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209),
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89),
TypeError: Cannot convert undefined or null to object,
    at Function.keys (<anonymous>),
    at Signin (/app/.next/server/pages/auth/signin.js:57:43),
    at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44),
    at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253),
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89),
    at $c (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98),
    at bd (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404),
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217),
    at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209),
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89),`

I know the issue is me, but I can't seem to figure it out. Since it's local, I did not set credentials, and I think that's where the issue is. But if that's the case, what are my options as GitHub or Google would require public facing, right?

Also, I only know enough to get myself I  trouble, obviously..

Great work tho!

### Reproduction

https://github.com/tj31moll/briefkasten

### System Info

```Shell
System:
    OS: Linux 4.19 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 Common KVM processor
    Memory: 3.53 GB / 4.53 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tj31moll** [comment]
![Screenshot_20220906-131003__01](https://user-images.githubusercontent.com/91799649/188698078-bd06be12-b9c4-4b22-a446-5d0db438e908.jpg)

Here is a screen shot of the landing page

**Comment by robotojomo** [comment]
It was a me issue. I didn't realize a login was required. Is there a way to have a local user list?

**Comment by tj31moll** [comment]
Ok I think I get it. You NEED to have a login configured. Is there an option for local. My workaround is maybe a local smtp server so this way it's all internal

**Comment by tj31moll** [comment]
> Hi @tj31moll, yes you need to have at least 1 login configured.
> 
> You can have google and github for local projects as well, I have a local github login setup for development. The redirect URL will then just be `http://localhost:3066/api/auth/callback/github` (for you, in the case of Github) 👍
> 
> You can create the github app here: https://github.com/settings/developers
> 
> More details for next-auth here: https://next-auth.js.org/providers/github

Yes, I was able to login in via GitHub. So docker is fully working.  I'm going to close this.

Maybe in the future, especially if we are self hosting internally, a local storage login can be configured but that's more a request and not a deficiency. I totally understand the logic tho. Appreciate the help and great work!!
