### ISSUE TITLE
Error while adding a new Tag

### ISSUE THREAD

**Issue by paulknulst** [ndom91/briefkasten#19]
### Describe the bug

Creating a new Tag in the sidebar will throw an error but still save the Tag within the database.

I already updated the source and got the following error within 
```
Error: [Immer] minified error nr: 4. Find the full error at: https://bit.ly/3cXEKWf
    at a (_app-62d4774c9ec39cc8.js:1:20196)
    at P (_app-62d4774c9ec39cc8.js:1:22206)
    at t.produce (_app-62d4774c9ec39cc8.js:1:26354)
    at _app-62d4774c9ec39cc8.js:1:26006
    at n (_app-62d4774c9ec39cc8.js:1:28102)
    at addTag (_app-62d4774c9ec39cc8.js:1:30311)
    at O (132.e5452ba71a226522.js:1:9124)
```

The error happens in the `sidebar.jsx` within  the function `saveQuickTag`

### Reproduction

Create a new tag from the sidebar

### System Info

```Shell
Build locally with Docker
Build remotely on Docker Swarm
Install it without Docker


  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 48.41 GB / 50.08 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
Thanks this clearly looks like a frontend JS error on my side, will take a look!

**Comment by ndom91** [comment]
Can confirm this is still an issue

**Comment by ndom91** [comment]
Hey folks, I've completely rewritten this project using SvelteKit. I've carried over almost all of the features from the original version, and so I'm going to close all existing issues.

If you're still interested in the project, I'd ask you to check out the latest verion (available at the same URL as always - https://briefkastenhq.com), and open a new issue if necessary 🙏
